# Generated by Django 4.2 on 2023-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('description_short', models.CharField(blank=True, max_length=200, verbose_name='Короткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='Длинное описание')),
                ('lng', models.FloatField(blank=True, verbose_name='Долгота')),
                ('lat', models.FloatField(blank=True, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Интересное место',
                'verbose_name_plural': 'Интересные места',
            },
        ),
    ]
