# Generated by Django 4.2 on 2023-06-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Заголовок'),
        ),
    ]
