# Generated by Django 4.2 on 2023-06-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_places_places_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='places_json',
        ),
    ]
