# Generated by Django 4.2 on 2023-06-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_places_places_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='sequence_number',
            field=models.IntegerField(default=1, verbose_name='Позиция'),
        ),
    ]
