# Generated by Django 4.2 on 2023-06-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_images_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='sequence_number',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
