# Generated by Django 4.2 on 2023-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_images_sequence_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['sequence_number'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='images',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Позиция'),
        ),
    ]
