# Generated by Django 4.2 on 2023-06-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_images_options_alter_images_sequence_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'ordering': ['sequence_number'], 'verbose_name': 'Интересное место', 'verbose_name_plural': 'Интересные места'},
        ),
        migrations.AddField(
            model_name='places',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Индекс в списке интересных мест'),
        ),
        migrations.AlterField(
            model_name='images',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Индекс в списке интересного места'),
        ),
    ]
