# Generated by Django 4.2 on 2023-06-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_places_options_places_sequence_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['place'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
