# Generated by Django 4.2.1 on 2023-06-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_rename_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
