# Generated by Django 4.2 on 2023-06-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_alter_image_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['sequence_number'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
